### ISSUE TITLE
React Dev tools are not available

### ISSUE THREAD

**Issue by fergusmeiklejohn** [sudomf/remix-vite#8] opened 2022-11-09 09:55 UTC
### Description

I find that booting the app with remix-vite I can't see the react dev tools.
I also find that the app isn't resolving exports, and isn't rendering any data in some routes, I've logged that the data is there but eg if I log `useMatches()` it logs on the server but not in the client, so I'm wondering if we have a hydration problem? It's that classic where it *seems* to be working because it's rendering HTML on the server but actually the client has a bug..?

### Library version

0.1.5

### Node version

16.17.0

**Comment by fergusmeiklejohn** [comment] 2022-11-10 01:30
I should have noted that the app runs normally with `remix dev`, I only see these bugs when it's run with `remix-vite`

**Comment by sudomf** [comment] 2022-11-10 12:47
Hey @fergusmeiklejohn. Thanks for the report. Can you please share a reproducible repo?

**Comment by sudomf** [comment] 2022-11-17 17:34
Closing it as I can't reproduce it. Feel free to reopen with a reproducible example.

**Closed as completed by sudomf** 2022-11-17 17:34 UTC
Labels: bug
